
modLoader="javafml" #mandatory
loaderVersion="[36,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="All rights reserved"
[[mods]] #mandatory
modId="goo_craft" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Goo Craft" #mandatory

logoFile="GooCraftLogo.png" #optional
authors="RedRoseWarrior1" #optional
description='''Brings the World of Goo game to Minecraft'''
[[dependencies.goo_craft]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[36,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.goo_craft]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
